voicemeeter_media_strip_id = 5
disabled_windows = []
wheel_dev_id = "USB\VID_XXXX&PID_XXXX&REV_XXXX" # hardware id from device manager

[[windows]]
process = "example_process"
class = "example_wmclass"
position = [ 2576, 633, 1618, 751 ]
transparency = 130

# Accent state should be an integer of
# ACCENT_DISABLED = 0
# ACCENT_ENABLE_GRADIENT = 1
# ACCENT_ENABLE_TRANSPARENTGRADIENT = 2
# ACCENT_ENABLE_BLURBEHIND = 3
# ACCENT_ENABLE_ACRYLICBLURBEHIND = 4
# ACCENT_ENABLE_TRANSPARANT = 6

# monitor should be the monitor index EXCEPT for the primary taskbar, which should be -1

[[taskbars]]
monitor = -1
accent_state = 0
hide_start = true
clock_to_start = true

[[taskbars]]
monitor = 1
accent_state = 6
position = [ 2560, 1400, 1913, 40 ] # x, y, width, height
hide_start = true
clock_to_start = true

[[taskbars]]
monitor = 2
accent_state = 6

[monitors]
1 = [ 2560, -720 ] # monitor index = x, y
