[window_transparency]
example_class = 200

# Accent state should be an integer of
# ACCENT_DISABLED = 0
# ACCENT_ENABLE_GRADIENT = 1
# ACCENT_ENABLE_TRANSPARENTGRADIENT = 2
# ACCENT_ENABLE_BLURBEHIND = 3
# ACCENT_ENABLE_ACRYLICBLURBEHIND = 4
# ACCENT_ENABLE_TRANSPARANT = 6

[taskbars.primary]
accent_state = 0
hide_start = true
clock_to_start = true

[taskbars.secondary]
accent_state = 6
position = [ 2560, 1400, 1913, 40 ] # x, y, width, height
hide_start = true
clock_to_start = true

[monitors]
1 = [ 2560, -720 ] # monitor index = x, y